export name=${1}
gsido mv TauTau_13_${1}-DYJets_svFit.root DY.root
gsido mv TauTau_13_${1}-DYJets1_svFit.root DY1.root
gsido mv TauTau_13_${1}-DYJets2_svFit.root DY2.root
gsido mv TauTau_13_${1}-DYJets3_svFit.root DY3.root
gsido mv TauTau_13_${1}-DYJets4_svFit.root DY4.root
gsido mv TauTau_13_${1}-EWKWMinus_svFit.root EWKWMinus.root
gsido mv TauTau_13_${1}-EWKWPlus_svFit.root EWKWPlus.root
gsido mv TauTau_13_${1}-EWKZ2l_svFit.root EWKZ2l.root
gsido mv TauTau_13_${1}-EWKZ2nu_svFit.root EWKZ2nu.root
gsido mv TauTau_13_${1}-T-tW_svFit.root T-tW.root
gsido mv TauTau_13_${1}-T-tchan.root T-tchan.root
gsido mv TauTau_13_${1}-T-tchan_svFit.root T-tchan.root
gsido mv TauTau_13_${1}-TT_svFit.root TT.root
gsido mv TauTau_13_${1}-Tbar-tW_svFit.root Tbar-tW.root
gsido mv TauTau_13_${1}-VBFHtoTauTau125_svFit.root VBF125.root
gsido mv TauTau_13_${1}-VBF_WW125_svFit.root VBF_WW125.root
gsido mv TauTau_13_${1}-VV_svFit.root VV.root
gsido mv TauTau_13_${1}-WJets_svFit.root W.root
gsido mv TauTau_13_${1}-WJets1_svFit.root W1.root
gsido mv TauTau_13_${1}-WJets2_svFit.root W2.root
gsido mv TauTau_13_${1}-WJets3_svFit.root W3.root
gsido mv TauTau_13_${1}-WJets4_svFit.root W4.root
gsido mv TauTau_13_${1}-WGLNu_svFit.root WGLNu.root
gsido mv TauTau_13_${1}-WGstarEE_svFit.root WGstarEE.root
gsido mv TauTau_13_${1}-WGstarMuMu_svFit.root WGstarMuMu.root
gsido mv TauTau_13_${1}-WWW_svFit.root WWW.root
gsido mv TauTau_13_${1}-WZ1l1nu2q_svFit.root WZ1l1nu2q.root
gsido mv TauTau_13_${1}-WZ1l3nu_svFit.root WZ1l3nu.root
gsido mv TauTau_13_${1}-WZ2l2q_svFit.root WZ2l2q.root
gsido mv TauTau_13_${1}-WZ3l1nu_svFit.root WZ3l1nu.root
gsido mv TauTau_13_${1}-WMinusHTauTau125_svFit.root WminusH125.root
gsido mv TauTau_13_${1}-WPlusHTauTau125_svFit.root WplusH125.root
gsido mv TauTau_13_${1}-ggH_WW125_svFit.root ggH_WW125.root
gsido mv TauTau_13_${1}-ggHtoTauTau125_svFit.root ggH125.root
gsido mv TauTau_13_${1}-ZHTauTau125_svFit.root ZH125.root
gsido mv TauTau_13_${1}-Tbar-tchan_svFit.root Tbar-tchan.root
